language: node_js
node_js:
- '10'
script:
- echo 'Testing Backend'
- cd sportify-backend
- echo 'Installing Dependencies'
- npm install
- npm install bcrypt
- echo 'Running test cases'
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: FLwvK2XU5Xx84Z8BpmwGpEINTBFQAa5w1UiUb9hAb3f/BqBqBw5EtMKOIV3O8RvLFKr3Mxcc0ihy0kbrXg2yO6yblobmcs/zmAGIV0OizOB+BEx0Eq+zSY7BzxPz/KG9NczJFX2frUgKpINHFD2xyEaKXeDX5rprlmg9o0eQjWVx+CLqLQ9w2kdGHA+uuM8qTfXARLM33KreBV6wuh6KWJyvHYtvtaSeshZO4gltVdt650n/iBL89ZDPBID6DcM/oJVsUyRUIcC6vzzNhzwmW6VGQd+pQWWb5grqdSB+6NaBzlnaL9ZVt8d0OhUj83RkTLDlEOuJqpTFhMDp0nmPKhTbBpnepTXebdGGXJiFLRttUfYNkOgrqUeHthdqovlYPVEqXdSoo4UeRksgJ+Hc14WCL2/wxHO6ZGwuzjwUdYU/10gfwFDZL+++2ET+rK9oM/QEcGhyax6NKfVA7Q5aEsKTumnARrt2HF5a3sgZQSitg/CGDRWF26xix+pJ9tGDYMUoLP2gDir9OMokeJgeHU+ViSsV85DFC6Dgd6Kdq1nNX90KD5MUgqn/h7ML6uA2EaSxSWCRvJQ2MTboh0hxnA0bC9NHN516+fCZBhpF+rifIdWN90D26XZcHpt5fTk28ux9TV5XObgxIGO1y9CbPIhj55z0QYM09nTRWTMjrXE=
  app: sportify-staging
  on:
    repo: cs130-w21/11
    branch: master
  skip_cleanup: 'true'
