language: node_js
node_js:
- '10'
script:
- echo 'Testing Backend'
- cd sportify-backend
- echo 'Installing Dependencies'
- npm install
- npm install bcrypt
- echo 'Running test cases'
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: CtkUftRDcCW+qlSgjTYYnvJhskNv6ZJttdsAom0uN65xfvMmOcgadPCUtZ2qEAToqaHkGgiu8CdLkmtfv2V3qnILztE4vhReRnh4bilEA51do+UKxJHQ+qjNWaLkSslWpegz2Qm/o33ZykzaGVI+BFLyaP6FMnOyIe6BmO5XgGPKOu55KeIL2ZdyGsl0NdmkhleoGHe6/IEct5Q4vawjZhl7VTBJG8aHDkNnZzV2Skiu+/c0jLn0PeWJgFYECr52L37YCyLlnmfFsKEBcqylPl6etc3cMwVpkaC/0QDakuEomuPrECY0OPrJd9dOpftcJwbStH3cN2gJr8zBoos+PWfwG19NABrdNFNx0V1qTUP9fSSuNzphsNPZdKdhO31r/vYyHIWvjxldnGJ72C5nVVc58+xu/kgeeBWHQ18lnaWct24QzginR5zi0wPoZo8j42eB/AInrQxs1Cubr9g8Ps/xAy9cQOaxyGpZbOMmYnjtZLPP0lIR8wNkWBP7rC2xJlkXArHW+4rkaMivCtyCQVzw5W9hrIXLvqZUermUxxm/eOtaLKIDNH4UwsyuL/3d6b2gV3UzIiiBlGuyY8S5zCc4TRFC7eepKeXoghmHWa+ioF95lIQAEfF13NaZ0HpKOMR2q0e/i0QCIW9quqnWKCjxdg1X39n5wLjJr40eZ1s=
  app: sportify-staging
  on:
    repo: cs130-w21/11
    branch: master
  skip_cleanup: 'true'
